name: Documentation 

on:
  push:
    branches: [ master ]

jobs:
  generateDocumentation:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build Toolkit
      run: |
        make build

    - name: Generate Script Commands Documentation
      run: |
        make gen-docs
        if `git status | grep -q "nothing to commit"`; then
          exit 0;
        else
          git config --local user.email "bot@raycast.com" &&
          git config --local user.name "Raycast Bot" &&
          mv extensions.md commands/README.md
          mv extensions.json commands/extensions.json
          git add commands/README.md commands/extensions.json &&
          git commit -m "Update Script Commands documentation" &&
          exit 0;
        fi
    
    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RAYCAST_BOT_ACCESS_TOKEN }}
        branch: ${{ github.ref }}
