name: Documentation

on:
  push:
    branches: [ master, Toolkit/Improvements ]

jobs:
  generateDocumentation:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Toolkit
        run: |
          make build

      - name: Generate Script Commands Documentation
        run: |
          make gen-docs-and-commit

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RAYCAST_BOT_ACCESS_TOKEN }}
          branch: ${{ github.ref }}

      - name: Re-pull on failure
        if: failure()
        run: git pull origin ${{ github.ref }} --autostash --rebase -X ours

      - name: Re-push on failure
        if: failure()
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
